FROM python:3.9-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR usr/src/app

COPY Pipfile Pipfile.lock ./
RUN pip install --upgrade pip &&\
    pip install --no-cache-dir pipenv &&\
    pipenv install --system --dev

COPY . .
